# -----------------------------------------------------------------------------
# Global script with various global vars and util functions.
# ----------------------------------------------------------------------------

extends Node

enum CARDBACKS {LOGO, SYMMETRIC}

enum ELEMENTS {
	PYRO, 
	HYDRO, 
	EARTH, 
	LIGHTNING, 
	FLORA, 
	ALLOY, 
	PRISMATIC, 
	WANED, 
	NONE, 
	ALL
}

var element2str: Dictionary = {
	ELEMENTS.PYRO: "pyro",
	ELEMENTS.HYDRO: "hydro",
	ELEMENTS.EARTH: "earth",
	ELEMENTS.LIGHTNING: "lightning",
	ELEMENTS.FLORA: "flora",
	ELEMENTS.ALLOY: "alloy",
	ELEMENTS.PRISMATIC: "prismatic",
	ELEMENTS.WANED: "waned",
	ELEMENTS.NONE: "nothing",
	ELEMENTS.ALL: "everything"
}

var element_strengths: Dictionary = {
	ELEMENTS.PYRO: [ELEMENTS.FLORA, ELEMENTS.ALLOY],
	ELEMENTS.HYDRO: [ELEMENTS.PYRO, ELEMENTS.EARTH],
	ELEMENTS.EARTH: [ELEMENTS.PYRO, ELEMENTS.LIGHTNING],
	ELEMENTS.LIGHTNING: [ELEMENTS.HYDRO, ELEMENTS.ALLOY],
	ELEMENTS.FLORA: [ELEMENTS.HYDRO, ELEMENTS.LIGHTNING],
	ELEMENTS.ALLOY: [ELEMENTS.EARTH, ELEMENTS.FLORA],
	ELEMENTS.PRISMATIC: [ELEMENTS.ALL],
	ELEMENTS.WANED: [ELEMENTS.NONE]
}

var element_weaknesses: Dictionary = {
	ELEMENTS.PYRO: [ELEMENTS.HYDRO, ELEMENTS.EARTH],
	ELEMENTS.HYDRO: [ELEMENTS.LIGHTNING, ELEMENTS.FLORA],
	ELEMENTS.EARTH: [ELEMENTS.HYDRO, ELEMENTS.ALLOY],
	ELEMENTS.LIGHTNING: [ELEMENTS.EARTH, ELEMENTS.FLORA],
	ELEMENTS.FLORA: [ELEMENTS.PYRO, ELEMENTS.ALLOY],
	ELEMENTS.ALLOY: [ELEMENTS.PYRO, ELEMENTS.LIGHTNING],
	ELEMENTS.PRISMATIC: [ELEMENTS.NONE],
	ELEMENTS.WANED: [ELEMENTS.ALL]
}
