# -----------------------------------------------------------------------------
# Global script with information about elements and util functions.
# ----------------------------------------------------------------------------

extends Node

enum ELEMENTS {PYRO, HYDRO, EARTH, LIGHTNING, FLORA, ALLOY, PRISMATIC, WANED, NONE, ALL}

var int2str: Dictionary = {
	ELEMENTS.PYRO: "Pyro",
	ELEMENTS.HYDRO: "Hydro",
	ELEMENTS.EARTH: "Earth",
	ELEMENTS.LIGHTNING: "Lightning",
	ELEMENTS.FLORA: "Flora",
	ELEMENTS.ALLOY: "Alloy",
	ELEMENTS.PRISMATIC: "Prismatic",
	ELEMENTS.WANED: "Waned",
	ELEMENTS.NONE: "Nothing",
	ELEMENTS.ALL: "Everything"
}

var strengths: Dictionary = {
	ELEMENTS.PYRO: [ELEMENTS.FLORA, ELEMENTS.ALLOY],
	ELEMENTS.HYDRO: [ELEMENTS.PYRO, ELEMENTS.EARTH],
	ELEMENTS.EARTH: [ELEMENTS.PYRO, ELEMENTS.LIGHTNING],
	ELEMENTS.LIGHTNING: [ELEMENTS.HYDRO, ELEMENTS.ALLOY],
	ELEMENTS.FLORA: [ELEMENTS.HYDRO, ELEMENTS.LIGHTNING],
	ELEMENTS.ALLOY: [ELEMENTS.EARTH, ELEMENTS.FLORA],
	ELEMENTS.PRISMATIC: [ELEMENTS.ALL],
	ELEMENTS.WANED: [ELEMENTS.NONE]
}

var weaknesses: Dictionary = {
	ELEMENTS.PYRO: [ELEMENTS.HYDRO, ELEMENTS.EARTH],
	ELEMENTS.HYDRO: [ELEMENTS.LIGHTNING, ELEMENTS.FLORA],
	ELEMENTS.EARTH: [ELEMENTS.HYDRO, ELEMENTS.ALLOY],
	ELEMENTS.LIGHTNING: [ELEMENTS.EARTH, ELEMENTS.FLORA],
	ELEMENTS.FLORA: [ELEMENTS.PYRO, ELEMENTS.ALLOY],
	ELEMENTS.ALLOY: [ELEMENTS.PYRO, ELEMENTS.LIGHTNING],
	ELEMENTS.PRISMATIC: [ELEMENTS.NONE],
	ELEMENTS.WANED: [ELEMENTS.ALL]
}
