name: "godot-ci export"

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: FusionForge
  PROJECT_PATH: project

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
