name: "godot-ci export"
on:
  push:
    branches:
      - '*'

permissions:
  actions: write
  contents: write

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: FusionForge
  PROJECT_PATH: project

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
        
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/${{ env.EXPORT_NAME }}-${{ env.TAG_NAME }}.exe
          
      - name: Zip the Exported Files
        run: |
          cd build/windows
          zip -r ../${{ env.EXPORT_NAME }}-${{ env.TAG_NAME }}.zip ./*
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
          
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/${{ env.EXPORT_NAME }}-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
